[package]
name = "rust-wasm"
version = "0.1.0"
authors = ["Scott Steele <scottlsteele@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
regex = "1"
seed = "0.4"
wasm-bindgen = "0.2.45"
